# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170725_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
